import { useState, useEffect } from 'react';
import { HashRouter, Routes, Route } from 'react-router-dom';
import { fetchReviewData } from './api';
import FileListPage from './pages/FileListPage';
import FileDetailPage from './pages/FileDetailPage';
import './App.css';

export default function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReviewData()
      .then(setData)
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <>
        <div className="header">
          <h1>X++ Code Review Dashboard</h1>
          <p className="subtitle">Automated review powered by xpp-code-reviewer agent</p>
        </div>
        <div className="loading">Loading review data...</div>
      </>
    );
  }

  if (!data) {
    return (
      <>
        <div className="header">
          <h1>X++ Code Review Dashboard</h1>
          <p className="subtitle">Automated review powered by xpp-code-reviewer agent</p>
          <div className="review-meta">
            <span>📄 <strong>—</strong></span>
            <span>🕐 <strong>—</strong></span>
            <span>📊 <strong>—</strong> issues found</span>
          </div>
        </div>
        <div className="container">
          <div className="empty-state">
            <h2>No Review Data</h2>
            <p>
              No <code>code-review-result.json</code> found. Run the{' '}
              <strong>xpp-code-reviewer</strong> agent to generate review data,
              then refresh this page.
            </p>
          </div>
        </div>
        <Footer />
      </>
    );
  }

  return (
    <HashRouter>
      <Routes>
        <Route path="/" element={<FileListPage data={data} />} />
        <Route path="/file/:fileName" element={<FileDetailPage data={data} />} />
      </Routes>
      <Footer date={data.date} />
    </HashRouter>
  );
}

function Footer({ date }) {
  return (
    <div className="footer">
      Generated by X++ Code Review Agent &bull;{' '}
      {date ? new Date(date).toLocaleString() : ''}
    </div>
  );
}
