import { useState, useEffect, useCallback } from 'react';
import { HashRouter, Routes, Route } from 'react-router-dom';
import { fetchReviewData, fetchProjects, switchProject, createProject, deleteProject } from './api';
import ProjectSwitcher from './components/ProjectSwitcher';
import FileListPage from './pages/FileListPage';
import FileDetailPage from './pages/FileDetailPage';
import DiffPage from './pages/DiffPage';
import './App.css';

export default function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [projectInfo, setProjectInfo] = useState({ activeProject: null, projects: {}, sourceCodePath: '' });

  const loadAll = useCallback(async () => {
    setLoading(true);
    const [reviewData, projData] = await Promise.all([
      fetchReviewData(),
      fetchProjects(),
    ]);
    setData(reviewData);
    setProjectInfo(projData);
    setLoading(false);
  }, []);

  useEffect(() => { loadAll(); }, [loadAll]);

  async function handleSwitchProject(name) {
    await switchProject(name);
    await loadAll();
  }

  async function handleCreateProject(proj) {
    await createProject(proj);
    await loadAll();
  }

  async function handleDeleteProject(name) {
    await deleteProject(name);
    await loadAll();
  }

  const projectProps = {
    activeProject: projectInfo.activeProject,
    projects: projectInfo.projects,
    onSwitch: handleSwitchProject,
    onCreate: handleCreateProject,
    onDelete: handleDeleteProject,
  };

  if (loading) {
    return (
      <>
        <div className="header">
          <h1>X++ Code Review Dashboard</h1>
          <p className="subtitle">Automated review powered by xpp-code-reviewer agent</p>
        </div>
        <div className="loading">Loading review data...</div>
      </>
    );
  }

  if (!data) {
    return (
      <>
        <div className="header">
          <div className="header-top-row">
            <div>
              <h1>X++ Code Review Dashboard</h1>
              <p className="subtitle">Automated review powered by xpp-code-reviewer agent</p>
            </div>
            <ProjectSwitcher {...projectProps} />
          </div>
          <div className="review-meta">
            <span>📄 <strong>—</strong></span>
            <span>🕐 <strong>—</strong></span>
            <span>📊 <strong>—</strong> issues found</span>
          </div>
        </div>
        <div className="container">
          <div className="empty-state">
            <h2>No Review Data</h2>
            <p>
              No <code>code-review-result.json</code> found. Run the{' '}
              <strong>xpp-code-reviewer</strong> agent to generate review data,
              then refresh this page.
            </p>
          </div>
        </div>
        <Footer />
      </>
    );
  }

  return (
    <HashRouter>
      <Routes>
        <Route path="/" element={<FileListPage data={data} projectProps={projectProps} />} />
        <Route path="/file/:fileName" element={<FileDetailPage data={data} projectProps={projectProps} />} />
        <Route path="/changes" element={<DiffPage data={data} projectProps={projectProps} />} />
      </Routes>
      <Footer date={data.date} />
    </HashRouter>
  );
}

function Footer({ date }) {
  return (
    <div className="footer">
      Generated by X++ Code Review Agent &bull;{' '}
      {date ? new Date(date).toLocaleString() : ''}
    </div>
  );
}
